### ISSUE TITLE
ycr script and instructions

### ISSUE THREAD

**Issue by fkromer** [bstubert/cuteradio#1]
I created a fork of your project and [added the ycr script and minimal instructions](https://github.com/bstubert/cuteradio/compare/master...fkromer:ycr). Let me know in case you accept a PR. Thanks for the great post about [Yocto Builds with CROPS containers](https://www.embeddeduse.com/2019/05/06/yocto-builds-with-crops-containers/) by the way!

**Comment by bstubert** [comment]
I am happy to accept your pull request. Do you need any extra authorisation?

**Comment by fkromer** [comment]
No, I don't need additional authorisation. I asked cause I have to adjust the instructions w.r.t. repo url before creating a PR.

**Comment by fkromer** [comment]
https://github.com/bstubert/cuteradio/pull/2
